package com.varian.mappercore.constant

class ParameterConstant {
    companion object {
        const val MSGMETADATA: String = "messageMetaData"
        const val CLOVERLOGGER: String = "cloverLogger"
        const val BUNDLE_MESSAGE = "bundleMessage"
        const val OUTCOME = "outcome"
        const val CLIENT_DECOR: String = "clientDecor"
        const val BUNDLE: String = "bundle"
        const val SIUOUT: String = "siu_out"
        const val BUNDLE_UTILITY: String = "bundleUtility"
        const val PARAMETERS_UTILITY: String = "parametersUtility"
        const val PATIENT_UTILITY: String = "patientUtility"
        const val SCRIPT_PATH: String = "scriptPath"
        const val SCRIPTS: String = "scripts"
        const val SEVERITY = "severity"
        const val HL7_MESSAGE = "hl7RawMessage"
        const val HL7_PARSER = "hl7Parser"
        const val PATIENT_SEARCH_KEYS = "patientSearchKeys"
        const val MERGE_PATIENT_SEARCH_KEYS = "mergePatientSearchKeys"
        const val PATIENT_MATCHING_TABLE = "patientMatchingTable"
        const val MESSAGE_CLOVERLEAF_ID = "messageCloverleafId"
        const val PROCESS_NAME = "processName"
        const val SITE_NAME = "siteName"
        const val SQL_UTILITY = "SqliteUtility"
        const val GLOBAL_INIT = "globalInit"
        const val INTERFACE_API_CLIENT = "interfaceApiClient"
        const val PATIENT_KEY_MAPPING_CONFIG = "patientKeyMapping"
        const val PARK_SERVICE = "parkService"
        const val TRACE_ID = "traceId"
        const val HL7_MESSAGE_OBJECT = "hl7Message"
        const val LOG="LOG"
        const val USER = "user"
        const val MAPPED_SQLITE_DB_NAME = "mappedSqliteDbName"
        const val SITE_DIR_NAME = "siteDirName"
        const val SQLITE_UTILITY = "SqliteUtility"
        const val EVENTS_MAPPING_TABLE = "EventsMapping"
        const val ATTACH_HOSPITAL_Departments = "AttachHospitalDepartments"
        const val SNAPSHOT_DEPARTMENTS = "SnapshotDepartments"
        const val UPDATE_PRIMARY_DEPARTMENT = "UpdatePrimaryDepartment"
        const val COVERAGE_POLICY_PLAN_TYPE = "policyPlanTypeValueSet"
        const val ALLERGY_CATEGORY_CODE = "allergyCategoryValueSet"
        const val HOSPITAL_DEPT_BUNDLE = "hospitalDeptBundle"
        const val USERDATA = "userdata"
        const val CREATEMESSAGE = "createmessage"
        const val parser="parser"

    }
}
